### ISSUE TITLE
elm-mdl should install with elm-package

### ISSUE THREAD

**Issue by kim0** [pdamoc/elm-mdl#1]
Else how can a user install it :)
I'm trying to play with some styled UI while learning elm .. Makes life spicy. elm-mdl is the best I could find

**Comment by pdamoc** [comment]
Unfortunately, this project was abandoned before reaching any usable state and I have no intention of pursuing this approach.

If you want to play with this approach just include the styles as I have 
https://github.com/pdamoc/elm-mdl/blob/master/src/Mdl.elm#L15-L20
or place Mdl.elm in your project and use regular elm-html.
